[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[build.args]
VITE_API_URL = "${{MIDDLEWARE_URL}}"

[deploy]
startCommand = "serve -s dist -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 30
